version: '3.7'

services:

  front:
    container_name: project-init
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:80'
    environment:
      NODE_ENV: production